=== puma startup: 2020-07-09 21:18:03 +0545 ===
=== puma startup: 2020-07-09 21:18:40 +0545 ===
=== puma startup: 2020-10-23 15:56:18 +0545 ===
=== puma startup: 2021-01-28 19:35:15 +0545 ===
=== puma startup: 2021-01-28 19:38:22 +0545 ===
#<Thread:0x00007f9bcfe392a8@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 19:38:55 +0545 ===
#<Thread:0x00007fc739ec7c20@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 19:39:22 +0545 ===
#<Thread:0x00007fa5750d9e28@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 19:40:24 +0545 ===
#<Thread:0x00007fc0fe3e7b20@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 19:40:32 +0545 ===
#<Thread:0x00007ffcf6f68740@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 19:40:49 +0545 ===
#<Thread:0x00007feb098be5b0@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 20:10:56 +0545 ===
#<Thread:0x00007f850cc8c8d0@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-28 20:11:57 +0545 ===
#<Thread:0x00007f99ac15dae0@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:17:54 +0545 ===
#<Thread:0x00007fe20b1ddbf8@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:19:13 +0545 ===
#<Thread:0x00007ffc628a3110@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:20:19 +0545 ===
#<Thread:0x00007fc8fece1fe8@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:22:06 +0545 ===
#<Thread:0x00007f7f0bb50928@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:24:31 +0545 ===
#<Thread:0x00007fe2d29d7eb8@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:24:52 +0545 ===
#<Thread:0x00007ffc9f0e86b8@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:30:48 +0545 ===
#<Thread:0x00007fcf37bc30f0@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:33:41 +0545 ===
#<Thread:0x00007fdc2fdf1368@/Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
/Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection': Error connecting to Redis on redis:6379 (SocketError) (Redis::CannotConnectError)
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:289:in `with_socket_timeout'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:139:in `call_loop'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:44:in `subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/subscribe.rb:14:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:3506:in `_subscription'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2326:in `block in subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:2325:in `subscribe'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:84:in `block in listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:75:in `block in with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
	from /Users/silwal/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:74:in `with_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/redis-4.2.1/lib/redis.rb:81:in `without_reconnect'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:81:in `listen'
	from /Users/silwal/.rvm/gems/ruby-2.5.1/gems/actioncable-6.0.3.4/lib/action_cable/subscription_adapter/redis.rb:155:in `block in ensure_listener_running'
=== puma startup: 2021-01-29 14:35:30 +0545 ===
